# Creates a trinityCore server for both auth and world server
FROM ubuntu:22.04

# squelches tzdata's install prompt
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y llibboost-all-dev \
    && apt-get install -y libboost-filesystem1.74-dev \
    && apt-get install -y libboost-system1.74 \
    && apt-get install -y libboost-filesystem1.74 \
    && apt-get install -y libboost-thread1.74 \
    && apt-get install -y libboost-program-options1.74 \
    && apt-get install -y libboost-iostreams1.74 \
    && apt-get install -y libboost-rege1.74 \
    && apt-get install -y mariadb-client \
    && apt-get install -y libmariadb-dev \
    && apt-get install -y libreadline8 \
    && adduser -q -u 1000 trinitycore

COPY . /opt/trinitycore

ENV DEBIAN_FRONTEND=

# by default, this containers will idle and do nothing. This is needed to easily run Trinity in "attended" mode
# when creating a clean server instance. Set the TrinityCore start process from Docker-compose file.
# See README.md for details
CMD ["/bin/bash", "-c", "while true ;sleep 5; do continue; done"]
